from rdkit import Chem
from rdkit.Chem import AllChem, rdFMCS

"""
        This script contains functions to compare the original and the
    relaxed structures of generated TMCs. These functions should verify:
        - The substructures of coordinating atoms
        - The atom connections of ligands
        - The metal oxidation states
    before and after TMC relaxations.
    
        A simple way to do so is to convert the relaxed TMC 3D geometries
    back to TMC-SMILES strings or RDKit molecule objects by xyz2mol_tmc.
    The embedded atom connections can then be compared, to verify the 2D
    consistency (with original TMC-SMILES) and 3D validity:
        - 2D molecular graphs:
            1. obvious steric clashes: redundant atom connections (e.g.,
            two anion ligands forming anion gas)
            2. disconnected fragments: missing bonds or multiple molecules
        - 3D geometries:
            xyz2mol inherits the 3D conformers from xyz files, so conformers
            are available to develop 3D-based validation methods using RDKit
            1. Decide if the TM 1-NN substructure is planar
                - PBF: plane of the best fit & the distances for out-of-
                plane atoms
            2. Compare the initial and the relaxed TM 1-NN substructure
                The initial one can be generated by RDKit, xTB, or UMA
                
            **Note**: current version of TMC-SMILES (xyz2mol_tmc) operates
            on final strings directly so the 3D information is lost.
            Need other approaches to change this.

        The script aims to build the toolbox to address the following
    concern (by a reviewer from RSC Chemical Science):
        A more systematic 3D/geometry-based validation: e.g., coordination
        geometry metrics (octahedral/tetrahedral/square planar distortion
        measures), detection of obvious steric clashes, and disconnected
        fragments after embedding/optimization

        Available tools in this script: (updating)
    1. get_tm_1NN:
        Extracting first nearest neighbor substructure around TM centers:
            - TM center
            - Coordinating atoms and dative bonds
            - Bonds between pairs of coordinating atoms
    Note: charges and radical electrons are preserved.

    2. identical_match:
        Match molecular 2D graph of substructures. Basically use mutual
    matches of HasSubstructMatch.

    3. compare_ligand_fragment_lists:
        (_ligand_fragment_comparison_key)
        Use canonical SMILES of ligand fragments as keys to match each one
    of ligand fragments. 

    4. compare_same_structure_different_charges:
        This is useful when comparing 1-NN substructures around TM atoms
    because xyz2mol_tmc may occasionally assign different charges even if
    3D geometries are similar.
        e.g., NH3->[Zn](<-NH3)(<-NH3)<-NH3
              [NH2-]->[Zn+2](<-NH3)(<-NH3)<-[NH2-]
        However, this approach is slow if the graphs are too large.

    Note: 
        - may ignore charge assignment, but will always ignore radical
        electron assignments. e.g., [C-2] and [C-] will be the same if
        setting 'ignoring charges' to true, but will be different by default.
        
        - will always ignore radical electron assignments. e.g., atoms with
        two radical electrons will always be identical with atoms with one
        radical electron.
         
        - will always consider bond orders. e.g., single bonds will differ
        from double or other bonds.

    5. compare_ligand_graph_lists:
        (_find_duplicate_ligand_graph_groups)
        (_maximum_bipartite_ligand_matching)
        (ligand_graph_keys_are_identical) -> compare just 1 pair of keys
        (make_ligand_fragment_graph_key)
        
"""

# Extract first-nearest-neighbor coordination substructure around a TM center

def get_tm_1NN(mol, tm_idx, use_original_idx_label=False,
               use_bond_info=False, use_molecule_info=False):
    """
    Extract the first-nearest-neighbor coordination substructure around a TM center.

    This function is designed for transition-metal complexes where the TM center is
    directly connected to coordinating atoms through dative bonds. The returned
    substructure contains:

    1. The TM center atom.
    2. All atoms directly connected to the TM center by dative bonds.
    3. All dative bonds between the TM center and coordinating atoms.
    4. All regular bonds among the coordinating atoms themselves.

    The returned molecule is useful for comparing local coordination environments.
    Atom order in the substructure is deterministic:

    - substructure atom 0 is always the TM center
    - subsequent atoms are coordinating atoms sorted by their original atom indices

    To make the substructure self-traceable, each atom receives these properties:

    - "original_atom_idx": atom index in the original molecule
    - "is_tm_center": "1" for the TM center, "0" otherwise
    - "is_coordinating_atom": "1" for coordinating atoms, "0" otherwise

    The substructure molecule itself receives these properties:

    - "tm_original_atom_idx"
    - "coord_original_atom_indices"

    Parameters
    ----------
    mol : rdkit.Chem.Mol
        Input TMC molecule.
    tm_idx : int
        Atom index of the TM center in the input molecule.

    Returns
    -------
    submol : rdkit.Chem.Mol
        First-nearest-neighbor coordination substructure.
    old_to_new : dict[int, int]
        Mapping from original atom indices to substructure atom indices.
    new_to_old : dict[int, int]
        Mapping from substructure atom indices to original atom indices.
    coord_atom_indices : list[int]
        Original atom indices of the coordinating atoms.
    """
    if not isinstance(tm_idx, int):
        raise TypeError("tm_idx must be an integer atom index.")

    if tm_idx < 0 or tm_idx >= mol.GetNumAtoms():
        raise ValueError(
            f"Invalid tm_idx={tm_idx}; molecule has {mol.GetNumAtoms()} atoms."
        )

    tm_atom = mol.GetAtomWithIdx(tm_idx)

    # -------------------------------------------------------------------------
    # 1. Identify coordinating atoms by dative bonds connected to the TM center.
    # -------------------------------------------------------------------------
    coord_atom_indices = []
    tm_coord_bond_indices = []

    for bond in tm_atom.GetBonds():
        if bond.GetBondType() != Chem.BondType.DATIVE:
            continue

        begin_idx = bond.GetBeginAtomIdx()
        end_idx = bond.GetEndAtomIdx()
        neighbor_idx = end_idx if begin_idx == tm_idx else begin_idx

        coord_atom_indices.append(neighbor_idx)
        tm_coord_bond_indices.append(bond.GetIdx())

    coord_atom_indices = sorted(set(coord_atom_indices))

    if len(coord_atom_indices) == 0:
        raise ValueError(
            f"No dative-bonded coordinating atoms found around atom {tm_idx}."
        )

    coord_set = set(coord_atom_indices)

    # Deterministic atom order for comparison:
    # TM center first, then coordinating atoms sorted by original atom index.
    atom_indices_to_keep = [tm_idx] + coord_atom_indices

    # -------------------------------------------------------------------------
    # 2. Create the new molecule and copy atoms with their existing properties.
    # -------------------------------------------------------------------------
    rw_submol = Chem.RWMol()
    old_to_new = {}

    for old_idx in atom_indices_to_keep:
        old_atom = mol.GetAtomWithIdx(old_idx)

        # Chem.Atom(old_atom) copies core RDKit atom information and atom props.
        new_atom = Chem.Atom(old_atom)

        # Add explicit traceability labels for downstream comparison.
        if use_original_idx_label:
            new_atom.SetIntProp("original_atom_idx", old_idx)
        new_atom.SetProp("is_tm_center", "1" if old_idx == tm_idx else "0")
        new_atom.SetProp(
            "is_coordinating_atom",
            "1" if old_idx in coord_set else "0",
        )

        new_idx = rw_submol.AddAtom(new_atom)
        old_to_new[old_idx] = new_idx

    # -------------------------------------------------------------------------
    # 3. Add relevant bonds:
    #    a) dative bonds between TM and coordinating atoms
    #    b) regular bonds among coordinating atoms
    # -------------------------------------------------------------------------
    tm_coord_bond_set = set(tm_coord_bond_indices)

    for bond in mol.GetBonds():
        begin_idx = bond.GetBeginAtomIdx()
        end_idx = bond.GetEndAtomIdx()

        is_tm_coord_dative_bond = bond.GetIdx() in tm_coord_bond_set
        is_coord_coord_bond = begin_idx in coord_set and end_idx in coord_set

        if not (is_tm_coord_dative_bond or is_coord_coord_bond):
            continue

        if begin_idx not in old_to_new or end_idx not in old_to_new:
            continue

        new_begin_idx = old_to_new[begin_idx]
        new_end_idx = old_to_new[end_idx]

        rw_submol.AddBond(new_begin_idx, new_end_idx, bond.GetBondType())
        new_bond = rw_submol.GetBondBetweenAtoms(new_begin_idx, new_end_idx)

        # Copy bond-level information useful for comparison.
        if use_bond_info:
            new_bond.SetIsAromatic(bond.GetIsAromatic())
            new_bond.SetStereo(bond.GetStereo())
            new_bond.SetBondDir(bond.GetBondDir())
            for key in bond.GetPropNames():
                new_bond.SetProp(key, bond.GetProp(key))

    submol = rw_submol.GetMol()

    # Add molecule-level traceability metadata.
    if use_molecule_info:
        submol.SetIntProp("tm_original_atom_idx", tm_idx)
        submol.SetProp(
            "coord_original_atom_indices",
            ",".join(str(idx) for idx in coord_atom_indices),
        )

    # Sanitization can fail for some organometallic representations. Using
    # catchErrors=True avoids destroying the molecule while still updating what
    # RDKit can safely update.
    Chem.SanitizeMol(submol, catchErrors=True) # <- very considerable by LLM!

    # Preserve conformer coordinates, if present.
    if mol.GetNumConformers() > 0:
        for conf in mol.GetConformers():
            new_conf = Chem.Conformer(submol.GetNumAtoms())
            new_conf.SetId(conf.GetId())
            new_conf.Set3D(conf.Is3D())

            for old_idx, new_idx in old_to_new.items():
                new_conf.SetAtomPosition(new_idx, conf.GetAtomPosition(old_idx))
            submol.AddConformer(new_conf, assignId=True)

    new_to_old = {new_idx: old_idx for old_idx, new_idx in old_to_new.items()}
    return submol, old_to_new, new_to_old, coord_atom_indices

def identical_match(submol1, submol2):
    """
    Compare two molecules equivalence, ignoring custom atom properties.
    """
    if submol1.GetNumAtoms() != submol2.GetNumAtoms():
        return False

    if submol1.GetNumBonds() != submol2.GetNumBonds():
        return False

    return (
        submol1.HasSubstructMatch(submol2)
        and submol2.HasSubstructMatch(submol1)
    )

# Compare ligand fragment lists after removing TM centers

def _ligand_fragment_comparison_key(
    mol,
    include_charges=True,
    include_stereochemistry=True,
    include_isotopes=True,
    ignore_atom_map_numbers=True,
    explicit_hydrogens=False,
):
    """
    Create a canonical comparison key for a ligand fragment.

    Custom atom properties from atom.SetProp(...) are ignored by canonical SMILES.
    Formal charges are included by default. Atom map numbers can optionally be
    cleared because they often encode provenance rather than chemistry.
    """
    mol_copy = Chem.Mol(mol)

    if ignore_atom_map_numbers:
        for atom in mol_copy.GetAtoms():
            atom.SetAtomMapNum(0)

    if not include_isotopes:
        for atom in mol_copy.GetAtoms():
            atom.SetIsotope(0)

    if not include_charges:
        for atom in mol_copy.GetAtoms():
            atom.SetFormalCharge(0)
            atom.SetNoImplicit(False)

    if explicit_hydrogens:
        mol_copy = Chem.AddHs(mol_copy)
    else:
        mol_copy = Chem.RemoveHs(mol_copy, sanitize=False)

    Chem.SanitizeMol(mol_copy, catchErrors=True)

    return Chem.MolToSmiles(
        mol_copy,
        canonical=True,
        isomericSmiles=include_stereochemistry,
    )

def compare_ligand_fragment_lists(
    ligand_frags_1,
    ligand_frags_2,
    include_charges=True,
    include_stereochemistry=True,
    include_isotopes=True,
    ignore_atom_map_numbers=True,
    explicit_hydrogens=False,
    require_unique_fragment_identity=False,
):
    """
    Compare two lists of ligand fragments after removing TM centers.

    Each ligand fragment from the first list is mapped to one identical ligand
    fragment in the second list. The comparison is performed as a multiset
    comparison using canonical RDKit SMILES keys, so the order of fragments in
    the two lists does not matter.

    Parameters
    ----------
    ligand_frags_1, ligand_frags_2 : list[rdkit.Chem.Mol]
        Ligand fragment molecules from two TMCs after TM removal.
    include_charges : bool, default=True
        If True, formal charges must match. If False, formal charges are ignored.
    include_stereochemistry : bool, default=True
        If True, stereochemical differences are considered different.
    include_isotopes : bool, default=True
        If True, isotope labels are considered part of the identity.
    ignore_atom_map_numbers : bool, default=True
        If True, atom map numbers are ignored. This is usually appropriate when
        atom map numbers are used only as provenance labels.
    explicit_hydrogens : bool, default=False
        If True, explicit hydrogens are included in the comparison key.
        If False, hydrogens are compared in RDKit's usual implicit-H manner.
    require_unique_fragment_identity : bool, default=False
        If False, repeated identical ligands are allowed and mapped
        deterministically by occurrence order.

        If True, each fragment identity may appear only once in each list.
        This stricter mode will fail for repeated identical ligands, such as two
        identical chloride ligands or two identical pyridine ligands.

    Returns
    -------
    result : dict
        Dictionary with these fields:

    - "same_ligand_multiset": bool
          True if the two ligand lists contain the same fragment identities with
          the same multiplicities.
        - "mapping_1_to_2": dict[int, int]
          Mapping from ligand_frags_1 index to ligand_frags_2 index.
        - "mapping_2_to_1": dict[int, int]
          Reverse mapping.
        - "unmatched_1": list[int]
          Fragments in ligand_frags_1 without matching fragments in list 2.
        - "unmatched_2": list[int]
          Fragments in ligand_frags_2 without matching fragments in list 1.
        - "duplicate_fragment_identities": dict[str, dict[str, list[int]]]
          Fragment identities that occur more than once in either list.
        - "fragment_keys_1": list[str]
          Canonical comparison keys for ligand_frags_1.
        - "fragment_keys_2": list[str]
          Canonical comparison keys for ligand_frags_2.
    """
    from collections import defaultdict, deque

    keys_1 = [
        _ligand_fragment_comparison_key(
            frag,
            include_charges=include_charges,
            include_stereochemistry=include_stereochemistry,
            include_isotopes=include_isotopes,
            ignore_atom_map_numbers=ignore_atom_map_numbers,
            explicit_hydrogens=explicit_hydrogens,
        )
        for frag in ligand_frags_1
    ]
    
    keys_2 = [
        _ligand_fragment_comparison_key(
            frag,
            include_charges=include_charges,
            include_stereochemistry=include_stereochemistry,
            include_isotopes=include_isotopes,
            ignore_atom_map_numbers=ignore_atom_map_numbers,
            explicit_hydrogens=explicit_hydrogens,
        )
        for frag in ligand_frags_2
    ]

    key_to_indices_1 = defaultdict(list)
    key_to_indices_2 = defaultdict(list)

    for idx, key in enumerate(keys_1):
        key_to_indices_1[key].append(idx)

    for idx, key in enumerate(keys_2):
        key_to_indices_2[key].append(idx)

    all_keys = sorted(set(key_to_indices_1) | set(key_to_indices_2))

    duplicate_fragment_identities = {}
    for key in all_keys:
        idxs_1 = key_to_indices_1.get(key, [])
        idxs_2 = key_to_indices_2.get(key, [])
        if len(idxs_1) > 1 or len(idxs_2) > 1:
            duplicate_fragment_identities[key] = {
                "list1_indices": idxs_1,
                "list2_indices": idxs_2,
            }

    if require_unique_fragment_identity and duplicate_fragment_identities:
        return {
            "same_ligand_multiset": False,
            "mapping_1_to_2": {},
            "mapping_2_to_1": {},
            "unmatched_1": list(range(len(ligand_frags_1))),
            "unmatched_2": list(range(len(ligand_frags_2))),
            "duplicate_fragment_identities": duplicate_fragment_identities,
            "fragment_keys_1": keys_1,
            "fragment_keys_2": keys_2,
            "reason": "Repeated identical fragment identities found while require_unique_fragment_identity=True.",
        }

    mapping_1_to_2 = {}
    mapping_2_to_1 = {}
    unmatched_1 = []
    unmatched_2 = []
    
    for key in all_keys:
        queue_1 = deque(key_to_indices_1.get(key, []))
        queue_2 = deque(key_to_indices_2.get(key, []))

        while queue_1 and queue_2:
            idx_1 = queue_1.popleft()
            idx_2 = queue_2.popleft()
            mapping_1_to_2[idx_1] = idx_2
            mapping_2_to_1[idx_2] = idx_1

        unmatched_1.extend(queue_1)
        unmatched_2.extend(queue_2)

    same_ligand_multiset = (
        len(unmatched_1) == 0
        and len(unmatched_2) == 0
        and len(ligand_frags_1) == len(ligand_frags_2)
    )

    return {
        "same_ligand_multiset": same_ligand_multiset,
        "mapping_1_to_2": dict(sorted(mapping_1_to_2.items())),
        "mapping_2_to_1": dict(sorted(mapping_2_to_1.items())),
        "unmatched_1": sorted(unmatched_1),
        "unmatched_2": sorted(unmatched_2),
        "duplicate_fragment_identities": duplicate_fragment_identities,
        "fragment_keys_1": keys_1,
        "fragment_keys_2": keys_2,
        "reason": "OK" if same_ligand_multiset else "Ligand fragment multisets differ.",
    }

# Compare same molecular structure with possibly different charge assignments

def compare_same_structure_different_charges(
    mol1,
    mol2,
    compare_bond_order=True,
    match_chirality=False,
    ring_matches_ring_only=True,
    complete_rings_only=False,
    max_matches=1000,
):
    """
    Determine whether two molecules have the same structure but different
    formal-charge assignments.

    This is useful when two TMC fragments or first-nearest-neighbor TM
    substructures have the same atom/bond graph but differ in where formal
    charges are assigned.

    The function proceeds in two conceptual steps:

    1. Compare molecular structure while ignoring formal charge.
       This uses RDKit MCS with atom comparison by element and bond comparison
       by bond order, unless compare_bond_order=False.

    2. If the structures are equivalent, examine all valid atom mappings and
       check whether formal charges can be matched under at least one mapping.

    Why all mappings?
    -----------------
    Symmetric molecules may have several equivalent atom mappings. A charge
    pattern that looks different under one mapping may actually be equivalent
    under another symmetry-equivalent mapping.

    Parameters
    ----------
    mol1, mol2 : rdkit.Chem.Mol
        Molecules to compare.
    compare_bond_order : bool, default=True
        If True, single/double/triple/dative/aromatic bond types must match.
        If False, only connectivity is compared.
    match_chirality : bool, default=False
        If True, require matching chirality in the structural comparison.
    ring_matches_ring_only : bool, default=True
        If True, ring atoms/bonds only match ring atoms/bonds.
    complete_rings_only : bool, default=False
        If True, MCS will only include complete rings.
    max_matches : int, default=1000
        Maximum number of atom mappings to inspect in each molecule.

    Returns
    -------
    result : dict
        Dictionary with the following keys:
        
        - "same_structure_ignoring_charges": bool
        - "same_charge_assignment_under_some_mapping": bool
        - "same_structure_but_different_charges": bool
        - "example_atom_mapping": list[tuple[int, int]] or None
          Atom index pairs mapping mol1 atoms to mol2 atoms.
        - "charge_differences": list[tuple[int, int, int, int]]
          Tuples of (mol1_atom_idx, mol2_atom_idx, mol1_charge, mol2_charge)
          for one representative mapping.
        - "mcs_smarts": str
    """
    if mol1.GetNumAtoms() != mol2.GetNumAtoms():
        return {
            "same_structure_ignoring_charges": False,
            "same_charge_assignment_under_some_mapping": False,
            "same_structure_but_different_charges": False,
            "example_atom_mapping": None,
            "charge_differences": [],
            "mcs_smarts": "",
        }

    if mol1.GetNumBonds() != mol2.GetNumBonds():
        return {
            "same_structure_ignoring_charges": False,
            "same_charge_assignment_under_some_mapping": False,
            "same_structure_but_different_charges": False,
            "example_atom_mapping": None,
            "charge_differences": [],
            "mcs_smarts": "",
        }

    mcs_params = rdFMCS.MCSParameters()
    mcs_params.AtomTyper = rdFMCS.AtomCompare.CompareElements
    mcs_params.BondTyper = (
        rdFMCS.BondCompare.CompareOrder
        if compare_bond_order
        else rdFMCS.BondCompare.CompareAny
    )
    mcs_params.MatchChiralTag = match_chirality
    mcs_params.RingMatchesRingOnly = ring_matches_ring_only
    mcs_params.CompleteRingsOnly = complete_rings_only
    mcs_params.MatchValences = False

    mcs_result = rdFMCS.FindMCS([mol1, mol2], mcs_params)

    same_structure = (
        not mcs_result.canceled
        and mcs_result.numAtoms == mol1.GetNumAtoms() == mol2.GetNumAtoms()
        and mcs_result.numBonds == mol1.GetNumBonds() == mol2.GetNumBonds()
    )

    if not same_structure:
        return {
            "same_structure_ignoring_charges": False,
            "same_charge_assignment_under_some_mapping": False,
            "same_structure_but_different_charges": False,
            "example_atom_mapping": None,
            "charge_differences": [],
            "mcs_smarts": mcs_result.smartsString,
        }

    mcs_query = Chem.MolFromSmarts(mcs_result.smartsString)
    if mcs_query is None:
        raise ValueError("Could not parse MCS SMARTS.")

    matches1 = mol1.GetSubstructMatches(mcs_query, uniquify=False, maxMatches=max_matches)
    matches2 = mol2.GetSubstructMatches(mcs_query, uniquify=False, maxMatches=max_matches)

    example_mapping = None
    example_charge_differences = None
    same_charge_assignment = False

    for match1 in matches1:
        for match2 in matches2:
            atom_mapping = list(zip(match1, match2))
            charge_differences = []

            for idx1, idx2 in atom_mapping:
                q1 = mol1.GetAtomWithIdx(idx1).GetFormalCharge()
                q2 = mol2.GetAtomWithIdx(idx2).GetFormalCharge()
                if q1 != q2:
                    charge_differences.append((idx1, idx2, q1, q2))

            if example_mapping is None:
                example_mapping = atom_mapping
                example_charge_differences = charge_differences

            if len(charge_differences) == 0:
                same_charge_assignment = True
                example_mapping = atom_mapping
                example_charge_differences = []
                break

        if same_charge_assignment:
            break

    return {
        "same_structure_ignoring_charges": True,
        "same_charge_assignment_under_some_mapping": same_charge_assignment,
        "same_structure_but_different_charges": not same_charge_assignment,
        "example_atom_mapping": example_mapping,
        "charge_differences": example_charge_differences or [],
        "mcs_smarts": mcs_result.smartsString,
    }

# Compare ligand fragment lists after removing TM centers using molecular graphs

def make_ligand_fragment_graph_key(
    mol,
    include_charges=True,
    include_stereochemistry=True,
    include_isotopes=True,
    ignore_atom_map_numbers=True,
    explicit_hydrogens=False,
    normalize_aromaticity=True,
):
    """
    Create a comparison-ready molecular graph key for a ligand fragment.

    This function intentionally returns an RDKit Mol object, not a SMILES string.
    The returned Mol is a cleaned/canonicalized *graph key* used for graph-based
    comparison with substructure matching.

    Custom atom properties from atom.SetProp(...) are preserved on the copy, but
    they are not used by ordinary RDKit substructure matching unless explicitly
    requested through SubstructMatchParameters.atomProperties.

    Parameters
    ----------
    mol : rdkit.Chem.Mol
        Input ligand fragment.
    include_charges : bool, default=True
        If True, formal charges are part of the graph key. If False, all formal
        charges are set to zero in the graph key.
    include_stereochemistry : bool, default=True
        If True, stereochemistry is retained. If False, atom and bond stereo are
        removed from the graph key.
    include_isotopes : bool, default=True
        If True, isotope labels are retained. If False, isotope labels are set
        to zero.
    ignore_atom_map_numbers : bool, default=True
        If True, atom map numbers are cleared. This is usually appropriate when
        atom map numbers encode provenance rather than chemistry.
    explicit_hydrogens : bool, default=False
        If True, explicit hydrogens are included in the graph key. If False,
        removable explicit hydrogens are removed before comparison.
    normalize_aromaticity : bool, default=True
        If True, RDKit attempts to normalize aromaticity. This can help reduce
        mismatches caused by different Kekule forms.

    Returns
    -------
    graph_key : rdkit.Chem.Mol
        A molecule graph suitable for graph-isomorphism comparison.
    """
    graph_key = Chem.Mol(mol)

    # Normalize explicit/implicit H representation before other simplifications.
    if explicit_hydrogens:
        graph_key = Chem.AddHs(graph_key, addCoords=True)
    else:
        # sanitize=False avoids failures for unusual charged or conjugated ligands.
        graph_key = Chem.RemoveHs(graph_key, sanitize=False)

    if ignore_atom_map_numbers:
        for atom in graph_key.GetAtoms():
            atom.SetAtomMapNum(0)

    if not include_isotopes:
        for atom in graph_key.GetAtoms():
            atom.SetIsotope(0)

    if not include_charges:
        for atom in graph_key.GetAtoms():
            atom.SetFormalCharge(0)

    if not include_stereochemistry:
        Chem.RemoveStereochemistry(graph_key)

    # Update property cache permissively so unusual ligand fragments do not fail.
    graph_key.UpdatePropertyCache(strict=False)

    if normalize_aromaticity:
        # catchErrors=True avoids raising on uncommon organometallic/ligand forms.
        # When successful, this helps make alternate Kekule depictions comparable.
        Chem.SanitizeMol(graph_key, catchErrors=True)

    return graph_key

def ligand_graph_keys_are_identical(
    graph_key_1,
    graph_key_2,
    include_stereochemistry=True,
    compare_bond_order=True,
    normalize_aromaticity=True,
):
    """
    Compare two ligand graph keys for graph equivalence.

    This avoids canonical SMILES entirely. In the default mode, it compares atom
    identities, bond connectivity, bond orders, aromaticity, formal charges if
    retained in the graph keys, isotope labels if retained in the graph keys,
    and stereochemistry if include_stereochemistry=True.

    Parameters
    ----------
    graph_key_1, graph_key_2 : rdkit.Chem.Mol
        Graph keys generated by make_ligand_fragment_graph_key().
    include_stereochemistry : bool, default=True
        Passed to RDKit substructure matching as useChirality.
    compare_bond_order : bool, default=True
        If True, use mutual HasSubstructMatch(), which requires compatible bond
        orders. If False, use an MCS comparison with CompareAny bonds, so only
        atom identity and connectivity are compared.
    normalize_aromaticity : bool, default=True
        If True and compare_bond_order=True, aromatic/conjugated differences are
        first reduced through the aromaticity normalization in graph-key creation.
        This argument is present for readability; normalization itself should be
        done when creating graph keys.

    Returns
    -------
    bool
        True if the two graph keys represent the same ligand graph under the
        chosen comparison settings.
    """
    if graph_key_1.GetNumAtoms() != graph_key_2.GetNumAtoms():
        return False

    if graph_key_1.GetNumBonds() != graph_key_2.GetNumBonds():
        return False

    if compare_bond_order:
        params = Chem.SubstructMatchParameters()
        params.useChirality = include_stereochemistry

        # Mutual substructure matching plus equal atom/bond counts is a graph
        # isomorphism test under RDKit's normal atom/bond query semantics.
        return (
            graph_key_1.HasSubstructMatch(graph_key_2, params)
            and graph_key_2.HasSubstructMatch(graph_key_1, params)
        )
    
    # Connectivity-only fallback. Useful for resonance/Kekule cases where you
    # want the same atom graph even if formal bond orders are assigned differently.
    mcs_params = rdFMCS.MCSParameters()
    mcs_params.AtomTyper = rdFMCS.AtomCompare.CompareElements
    mcs_params.BondTyper = rdFMCS.BondCompare.CompareAny
    mcs_params.MatchChiralTag = include_stereochemistry
    mcs_params.MatchValences = False

    mcs_result = rdFMCS.FindMCS([graph_key_1, graph_key_2], mcs_params)

    return (
        not mcs_result.canceled
        and mcs_result.numAtoms == graph_key_1.GetNumAtoms() == graph_key_2.GetNumAtoms()
        and mcs_result.numBonds == graph_key_1.GetNumBonds() == graph_key_2.GetNumBonds()
    )

def _maximum_bipartite_ligand_matching(match_matrix):
    """
    Internal helper: maximum one-to-one matching from list 1 to list 2.
    """
    n1 = len(match_matrix)
    n2 = len(match_matrix[0]) if n1 > 0 else 0

    # Try more constrained fragments first for deterministic behavior.
    order = sorted(
        range(n1),
        key=lambda i: (sum(1 for value in match_matrix[i] if value), i),
    )

    match_2_to_1 = {}

    def try_assign(i, seen_2):
        candidate_js = [j for j, value in enumerate(match_matrix[i]) if value]
        for j in candidate_js:
            if j in seen_2:
                continue
            seen_2.add(j)

            if j not in match_2_to_1 or try_assign(match_2_to_1[j], seen_2):
                match_2_to_1[j] = i
                return True

        return False

    for i in order:
        try_assign(i, set())

    mapping_1_to_2 = {i: j for j, i in match_2_to_1.items()}
    mapping_2_to_1 = dict(match_2_to_1)

    unmatched_1 = [i for i in range(n1) if i not in mapping_1_to_2]
    unmatched_2 = [j for j in range(n2) if j not in mapping_2_to_1]

    return mapping_1_to_2, mapping_2_to_1, unmatched_1, unmatched_2

def _find_duplicate_ligand_graph_groups(
    graph_keys,
    include_stereochemistry=True,
    compare_bond_order=True,
):
    """
    Internal helper: identify repeated identical ligand graphs within one list.
    """
    n = len(graph_keys)
    parent = list(range(n))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a, b):
        root_a = find(a)
        root_b = find(b)
        if root_a != root_b:
            parent[root_b] = root_a

    for i in range(n):
        for j in range(i + 1, n):
            if ligand_graph_keys_are_identical(
                graph_keys[i],
                graph_keys[j],
                include_stereochemistry=include_stereochemistry,
                compare_bond_order=compare_bond_order,
            ):
                union(i, j)

    groups = {}
    for i in range(n):
        groups.setdefault(find(i), []).append(i)

    return [sorted(indices) for indices in groups.values() if len(indices) > 1]

def compare_ligand_graph_lists(
    ligand_frags_1,
    ligand_frags_2,
    include_charges=True,
    include_stereochemistry=True,
    include_isotopes=True,
    ignore_atom_map_numbers=True,
    explicit_hydrogens=False,
    require_unique_fragment_identity=False,
    compare_bond_order=True,
    normalize_aromaticity=True,
):
    """
    Compare two lists of ligand fragments after removing TM centers.

    This version compares ligand fragments by molecular graph isomorphism rather
    than canonical SMILES. This avoids failures where two equivalent ligand
    graphs produce different canonical SMILES due to atom ordering, resonance, or
    Kekule representation.

    Each ligand fragment in ligand_frags_1 is assigned to at most one identical
    fragment in ligand_frags_2, and vice versa.

    Parameters
    ----------
    ligand_frags_1, ligand_frags_2 : list[rdkit.Chem.Mol]
        Ligand fragment molecules from two TMCs after TM removal.
    include_charges : bool, default=True
        If True, formal charges are considered. If False, charges are ignored.
    include_stereochemistry : bool, default=True
        If True, stereochemical differences are considered different.
    include_isotopes : bool, default=True
        If True, isotope labels are considered part of the identity.
    ignore_atom_map_numbers : bool, default=True
        If True, atom map numbers are ignored.
    explicit_hydrogens : bool, default=False
        If True, explicit hydrogens are included in the comparison graph.
        If False, removable explicit hydrogens are ignored.
    require_unique_fragment_identity : bool, default=False
        If True, repeated identical ligand fragments within either list are
        treated as ambiguous and the comparison fails.
    compare_bond_order : bool, default=True
        If True, bond orders must match. If False, compare only atom identity and
        connectivity. Setting this to False is useful for difficult resonance or
        Kekule-assignment cases, but it will also ignore chemically meaningful
        single/double/triple differences.
    normalize_aromaticity : bool, default=True
        If True, RDKit attempts aromaticity normalization before comparison.

    Returns
    -------
    result : dict
        Dictionary with these fields:
        
        - "same_ligand_graphs": bool
        - "mapping_1_to_2": dict[int, int]
        - "mapping_2_to_1": dict[int, int]
        - "unmatched_1": list[int]
        - "unmatched_2": list[int]
        - "candidate_matches_1_to_2": dict[int, list[int]]
        - "duplicate_fragment_identities": dict[str, list[list[int]]]
        - "match_matrix": list[list[bool]]
        - "graph_keys_1": list[rdkit.Chem.Mol]
        - "graph_keys_2": list[rdkit.Chem.Mol]
        - "reason": str
    """
    graph_keys_1 = [
        make_ligand_fragment_graph_key(
            frag,
            include_charges=include_charges,
            include_stereochemistry=include_stereochemistry,
            include_isotopes=include_isotopes,
            ignore_atom_map_numbers=ignore_atom_map_numbers,
            explicit_hydrogens=explicit_hydrogens,
            normalize_aromaticity=normalize_aromaticity,
        )
        for frag in ligand_frags_1
    ]

    graph_keys_2 = [
        make_ligand_fragment_graph_key(
            frag,
            include_charges=include_charges,
            include_stereochemistry=include_stereochemistry,
            include_isotopes=include_isotopes,
            ignore_atom_map_numbers=ignore_atom_map_numbers,
            explicit_hydrogens=explicit_hydrogens,
            normalize_aromaticity=normalize_aromaticity,
        )
        for frag in ligand_frags_2
    ]

    """
        Note: the function doesn't truly apply removing duplicated ligands
        when making comparisons.
    """
    duplicate_groups_1 = _find_duplicate_ligand_graph_groups(
        graph_keys_1,
        include_stereochemistry=include_stereochemistry,
        compare_bond_order=compare_bond_order,
    )
    duplicate_groups_2 = _find_duplicate_ligand_graph_groups(
        graph_keys_2,
        include_stereochemistry=include_stereochemistry,
        compare_bond_order=compare_bond_order,
    )

    duplicate_fragment_identities = {
        "list1_duplicate_groups": duplicate_groups_1,
        "list2_duplicate_groups": duplicate_groups_2,
    }
    
    if require_unique_fragment_identity and (duplicate_groups_1 or \
                                             duplicate_groups_2):
        return {
            "same_ligand_graphs": False,
            "mapping_1_to_2": {},
            "mapping_2_to_1": {},
            "unmatched_1": list(range(len(ligand_frags_1))),
            "unmatched_2": list(range(len(ligand_frags_2))),
            "candidate_matches_1_to_2": {},
            "duplicate_fragment_identities": duplicate_fragment_identities,
            "match_matrix": [],
            "graph_keys_1": graph_keys_1,
            "graph_keys_2": graph_keys_2,
            "reason": "Repeated identical ligand graphs found while require_unique_fragment_identity=True.",
        }

    match_matrix = []
    for key_1 in graph_keys_1:
        row = []
        for key_2 in graph_keys_2:
            row.append(
                ligand_graph_keys_are_identical(
                    key_1,
                    key_2,
                    include_stereochemistry=include_stereochemistry,
                    compare_bond_order=compare_bond_order,
                    normalize_aromaticity=normalize_aromaticity,
                )
            )
        match_matrix.append(row)

    candidate_matches_1_to_2 = {
        i: [j for j, is_match in enumerate(row) if is_match]
        for i, row in enumerate(match_matrix)
    }

    mapping_1_to_2, mapping_2_to_1, unmatched_1, unmatched_2 = (
        _maximum_bipartite_ligand_matching(match_matrix)
    )

    same_ligand_graphs = (
        len(ligand_frags_1) == len(ligand_frags_2)
        and len(unmatched_1) == 0
        and len(unmatched_2) == 0
    )

    if same_ligand_graphs:
        reason = "OK"
    elif len(ligand_frags_1) != len(ligand_frags_2):
        reason = "Different numbers of ligand fragments."
    else:
        reason = "Could not find a complete one-to-one ligand graph matching."

    return {
        "same_ligand_graphs": same_ligand_graphs,
        # Backward-compatible alias for the previous SMILES-key implementation.
        "same_ligand_multiset": same_ligand_graphs,
        "mapping_1_to_2": dict(sorted(mapping_1_to_2.items())),
        "mapping_2_to_1": dict(sorted(mapping_2_to_1.items())),
        "unmatched_1": sorted(unmatched_1),
        "unmatched_2": sorted(unmatched_2),
        "candidate_matches_1_to_2": candidate_matches_1_to_2,
        "duplicate_fragment_identities": duplicate_fragment_identities,
        "match_matrix": match_matrix,
        "graph_keys_1": graph_keys_1,
        "graph_keys_2": graph_keys_2,
        "reason": reason,
    }
